/**
 * Scans public/ for *.gpx files and writes src/gpxFiles.ts.
 * Runs automatically via "prestart" / "prebuild" npm hooks.
 */
const fs   = require("fs");
const path = require("path");

const publicDir  = path.join(__dirname, "..", "public");
const outputFile = path.join(__dirname, "..", "src", "gpxFiles.ts");

const gpxFiles = fs
  .readdirSync(publicDir)
  .filter((f) => f.toLowerCase().endsWith(".gpx"))
  .sort();

const content =
  `// Auto-generated by scripts/syncGpxFiles.cjs — do not edit manually.\n` +
  `// Re-runs automatically on "npm start" and "npm run build".\n` +
  `// To refresh manually: node scripts/syncGpxFiles.cjs\n\n` +
  `export const GPX_FILES = ${JSON.stringify(gpxFiles, null, 2)} as const;\n` +
  `export type GpxFileName = typeof GPX_FILES[number];\n`;

fs.writeFileSync(outputFile, content, "utf8");
console.log(`[sync-gpx] Found ${gpxFiles.length} GPX file(s):`, gpxFiles);
