// Auto-generated by scripts/syncGpxFiles.cjs — do not edit manually.
// Re-runs automatically on "npm start" and "npm run build".
// To refresh manually: node scripts/syncGpxFiles.cjs

export const GPX_FILES = [
  "Glenha-Bikerafting-Loop.gpx",
  "Green_Divide.gpx",
  "ghent-to-lauris.gpx"
] as const;
export type GpxFileName = typeof GPX_FILES[number];
