import { z } from "zod";
import { zColor } from "@remotion/zod-types";
import { GPX_FILES } from "./gpxFiles";

// "" = no file selected; rest are filenames from /public (auto-generated by scripts/syncGpxFiles.cjs)
const gpxOptions = ["", ...GPX_FILES] as [string, ...string[]];

export const schema = z.object({
  mode:         z.enum(["directions", "gpx"]).default("directions"),
  gpxFile:      z.enum(gpxOptions).default(""),
  startAddress: z.string().default("Ghent, Belgium"),
  endAddress:   z.string().default("Lauris, France"),
  startLabel:   z.string().default("Ghent"),
  endLabel:     z.string().default("Lauris"),
  zoomMode:     z.enum(["auto", "manual"]).default("auto"),
  zoom:         z.number().min(1).max(20).multipleOf(0.1).default(5.5),
  lineColor:    zColor().default("#e53935"),
  lineWidth:    z.number().min(1).max(20).default(4),
  lineStyle:      z.enum(["solid", "dashed", "dotted", "long-dash", "dash-dot", "pencil"]).default("solid"),
  pencilStrength: z.number().min(1).max(10).default(5),
  labelBgColor:    zColor().default("#555555"),
  labelTextColor:  zColor().default("#ffffff"),
  minPopulation:   z.number().min(0).max(15_000_000).default(100_000), // city label filter
  duration:        z.number().min(1).max(60).default(5), // seconds
});

export type MapSchema = z.infer<typeof schema>;
