import { z } from "zod";
import { zColor } from "@remotion/zod-types";
import { GPX_FILES } from "./gpxFiles";

// "" = no file selected; rest are filenames from /public (auto-generated by scripts/syncGpxFiles.cjs)
const gpxOptions = ["", ...GPX_FILES] as [string, ...string[]];

export const schema = z.object({
  /** Animation mode.
   *  directions = point-to-point route (geocoded addresses + routing API)
   *  gpx        = pre-recorded track from a .gpx file */
  mode: z.enum(["directions", "gpx"]).default("directions"),

  /** GPX filename from /public. Only used when mode === "gpx".
   *  Options are auto-generated by scripts/syncGpxFiles.cjs → src/gpxFiles.ts */
  gpxFile: z.enum(gpxOptions).default(""),

  /** Travel mode for point-to-point routing. Only used when mode === "directions".
   *  driving  → Mapbox Directions API (fast, accurate, any distance)
   *  cycling  → routing.openstreetmap.de/routed-bike (no API key, handles long distances)
   *  walking  → routing.openstreetmap.de/routed-foot (no API key, handles long distances)
   *  flight   → great-circle arc computed locally via d3-geo (no API call, always available)
   *  Mapbox is not used for cycling/walking because it rejects routes longer than ~24 h. */
  travelMode: z.enum(["driving", "cycling", "walking", "flight"]).default("driving"),

  /** Start location as a free-text address. Geocoded via Mapbox Geocoding API. */
  startAddress: z.string().default("Ghent, Belgium"),

  /** End location as a free-text address. Geocoded via Mapbox Geocoding API. */
  endAddress: z.string().default("Lauris, France"),

  /** Label shown at the start pin. Defaults to the city name but can be anything. */
  startLabel: z.string().default("Ghent"),

  /** Label shown at the end pin. Defaults to the city name but can be anything. */
  endLabel: z.string().default("Lauris"),

  /** Mapbox style slug (e.g. "mapbox/streets-v12") or "none" for a plain background.
   *  When "none", the map tile is not rendered and mapBgColor is used instead.
   *  Custom styles use the format "username/styleId" from your Mapbox account.
   *  Reads MAPBOX_STYLE from .env; falls back to the public "mapbox/light-v11" style
   *  so the app works out-of-the-box without a personal style. */
  mapStyle: z.string().default(process.env.MAPBOX_STYLE || 'mapbox/light-v11'),

  /** Background color shown when mapStyle === "none". Ignored otherwise. */
  mapBgColor: zColor().default("#ffffff"),

  /** auto = zoom is calculated to fit the route with padding.
   *  manual = use the zoom value below. */
  zoomMode: z.enum(["auto", "manual"]).default("auto"),

  /** Map zoom level (1–20). Only used when zoomMode === "manual".
   *  ~5 = country scale, ~8 = region, ~12 = city, ~15 = street. */
  zoom: z.number().min(1).max(20).multipleOf(0.1).default(5.5),

  /** Color of the route line. Supports 6-char (#RRGGBB) or 8-char (#RRGGBBAA) hex for opacity. */
  lineColor: zColor().default("#e53935"),

  /** Stroke width of the route line in SVG units (~pixels at 1080px canvas width). */
  lineWidth: z.number().min(1).max(30).default(10),

  /** Radius in SVG canvas pixels of the start and end pin dots.
   *  The fill colour always matches lineColor. */
  pinSize: z.number().min(2).max(24).default(6),

  /** Visual style of the route line.
   *  solid, dashed, dotted, long-dash, dash-dot = standard SVG stroke patterns
   *  pencil = hand-drawn effect with noise (strength controlled by pencilStrength) */
  lineStyle: z.enum(["solid", "dashed", "dotted", "long-dash", "dash-dot", "pencil"]).default("solid"),

  /** Roughness of the pencil/hand-drawn line effect (1 = subtle, 10 = very rough).
   *  Only used when lineStyle === "pencil". */
  pencilStrength: z.number().min(1).max(10).default(5),

  /** Icon rendered at the tip of the route line as it draws across the screen.
   *  'none' = disabled. All other values show a circular badge (same colour as
   *  the route line) with a white vehicle silhouette that rotates to follow the
   *  direction of travel. */
  routeMarker: z.enum(['none', 'car', 'camper', 'plane', 'bike', 'walk']).default('none'),

  /** Diameter of the circular route marker badge in SVG canvas pixels.
   *  Only used when routeMarker !== 'none'. */
  routeMarkerSize: z.number().min(20).max(120).default(60),

  /** Whether to show animated labels at the start and end pins.
   *  animated = labels animate in during the video
   *  on       = labels are always fully visible (good for thumbnails)
   *  off      = no labels */
  labelMode: z.enum(["animated", "on", "off"]).default("animated"),

  /** Animation style for label reveal. Only used when labelMode === "animated".
   *  Options: left-to-right, right-to-left, fade, scale, slide-up, typewriter, wipe-from-dot */
  labelAnimation: z.enum([
    "left-to-right", "right-to-left", "fade", "scale",
    "slide-up", "typewriter", "wipe-from-dot",
  ]).default("left-to-right"),

  /** Font family used for the start/end label boxes. Same options as cityFont. */
  labelFont: z.enum(["Helvetica", "Inter", "Georgia", "Oswald", "Merriweather"]).default("Helvetica"),

  /** Background fill color of the start/end label boxes. Supports alpha via 8-char hex. */
  labelBgColor: zColor().default("#555555"),

  /** Text color inside the start/end label boxes. */
  labelTextColor: zColor().default("#ffffff"),

  /** Minimum city population to show as a dot + label overlay on the map.
   *  0 = hide all cities. Thresholds: 10k / 50k / 100k / 500k / 1M / 2M. */
  minPopulation: z.number().min(0).max(15_000_000).default(100_000),

  /** Font family used for city name labels. */
  cityFont: z.enum(["Helvetica", "Inter", "Georgia", "Oswald", "Merriweather"]).default("Helvetica"),

  /** Whether to render city names in ALL CAPS. */
  cityUppercase: z.boolean().default(false),

  /** Text color for large cities (population ≥ 1M). Supports alpha. */
  cityColorBig: zColor().default("#333333"),

  /** Text color for medium cities (population 100k–1M). Supports alpha. */
  cityColorMedium: zColor().default("#555555"),

  /** Text color for small cities (population < 100k). Supports alpha. */
  cityColorSmall: zColor().default("#999999"),

  /** Font size for large city labels (px at 1080px canvas width). */
  citySizeBig: z.number().min(10).max(80).default(44),

  /** Font size for medium city labels. */
  citySizeMedium: z.number().min(8).max(60).default(31),

  /** Font size for small city labels. */
  citySizeSmall: z.number().min(6).max(44).default(22),

  /** How much the flight arc bows away from the straight line (0 = flat great-circle,
   *  100 = very pronounced arc). Applied in screen space perpendicular to the chord.
   *  Only used when travelMode === "flight". */
  flightCurve: z.number().min(0).max(100).default(40),

  /** Total animation duration in seconds. Affects render length and animation timing. */
  duration: z.number().min(1).max(60).default(5),

  /** Output canvas format. Controls width × height passed to Remotion.
   *  portrait  = 1080 × 1920 (9:16 — vertical, default — short-form social video)
   *  landscape = 1920 × 1080 (16:9 — YouTube / widescreen)
   *  square    = 1080 × 1080 (1:1 — Instagram feed) */
  outputFormat: z.enum(['portrait', 'landscape', 'square', 'instagram-post']).default('portrait'),

  /** Show an elevation profile chart at the bottom of the canvas.
   *  Only rendered in GPX mode when the file contains <ele> data. */
  showElevationProfile: z.boolean().default(false),

  /** Stroke and fill colour for the elevation profile line and area. */
  elevationColor: zColor().default('#333333'),

  /** Background fill of the elevation profile box. Supports alpha via 8-char hex. */
  elevationBgColor: zColor().default('#ffffffcc'),

  /** Left edge of the elevation box as % of canvas width (0 = far left). */
  elevationLeft:   z.number().min(0).max(90).default(4),

  /** Top edge of the elevation box as % of canvas height (0 = top, 85 ≈ bottom). */
  elevationTop:    z.number().min(0).max(95).default(85),

  /** Width of the elevation box as % of canvas width. */
  elevationWidth:  z.number().min(10).max(100).default(92),

  /** Height of the elevation box as % of canvas height. */
  elevationHeight: z.number().min(3).max(50).default(11),
});

export type MapSchema = z.infer<typeof schema>;
